const voices = [
    {   name: "Alexa",
        description: "Default",
        language: "",
        locale: "en-US",
        sex: "female",
        flagImageURL: "./images/alexa_logo2.png",
        flagImageAltText: "Alexa flag",
    },
    {
        name: "Justin",
        description: "American boy",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "male",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Joey",
        description: "American male",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "male",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Matthew",
        description: "American male two",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "male",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Ivy",
        description: "American girl",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "female",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Joanna",
        description: "American female",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "female",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Kendra",
        description: "American female two",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "female",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Kimberly",
        description: "American female three",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "female",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Salli",
        description: "American female four",
        accent: "American",
        language: "English",
        locale: "en-US",
        sex: "female",
        flagImageURL: "./images/us_flag_round.png",
        flagImageAltText: "US flag",
    },
    {
        name: "Russell",
        description: "Australian male",
        accent: "Australian",
        language: "English",
        locale: "en-AU",
        sex: "male",
        flagImageURL: "./images/australia_flag_round.png",
        flagImageAltText: "Australia flag",
    },
    {
        name: "Nicole",
        description: "Australian female",
        accent: "Australian",
        language: "English",
        locale: "en-AU",
        sex: "female",
        flagImageURL: "./images/australia_flag_round.png",
        flagImageAltText: "Australia flag",
    },
    {
        name: "Brian",
        description: "British male",
        accent: "British",
        language: "English",
        locale: "en-GB",
        sex: "male",
        flagImageURL: "./images/uk_flag_round.png",
        flagImageAltText: "UK flag",
    },
    {
        name: "Amy",
        description: "British female",
        accent: "British",
        language: "English",
        locale: "en-GB",
        sex: "female",
        flagImageURL: "./images/uk_flag_round.png",
        flagImageAltText: "UK flag",
    },
    {
        name: "Emma",
        description: "British female two",
        accent: "British",
        language: "English",
        locale: "en-GB",
        sex: "female",
        flagImageURL: "./images/uk_flag_round.png",
        flagImageAltText: "UK flag",
    },
    {
        name: "Aditi",
        description: "Indian female",
        accent: "Indian",
        language: ["English", "Hindi"],
        locale: ["en-IN", "hi-IN"],
        sex: "female",
        flagImageURL: "./images/india_flag_round.png",
        flagImageAltText: "India flag",
    },
    {
        name: "Raveena",
        description: "Indian female two",
        accent: "Indian",
        language: "English",
        locale: "en-IN",
        sex: "female",
        flagImageURL: "./images/india_flag_round.png",
        flagImageAltText: "India flag",
    },
    {
        name: "Chantal",
        description: "French female three",
        accent: "French",
        language: "French",
        locale: "fr-CA",
        sex: "female",
        flagImageURL: "./images/canada_flag_round.png",
        flagImageAltText: "Canada flag",
    },
    {
        name: "Mathieu",
        description: "French male",
        accent: "French",
        language: "French",
        locale: "fr-FR",
        sex: "male",
        flagImageURL: "./images/france_flag_round.png",
        flagImageAltText: "French flag",
    },
    {
        name: "Celine",
        description: "French female",
        accent: "French",
        language: "French",
        locale: "fr-FR",
        sex: "female",
        flagImageURL: "./images/france_flag_round.png",
        flagImageAltText: "French flag",
    },
    {
        name: "Lea",
        description: "French female two",
        accent: "French",
        language: "French",
        locale: "fr-FR",
        sex: "female",
        flagImageURL: "./images/france_flag_round.png",
        flagImageAltText: "French flag",
    },
    {
        name: "Hans",
        description: "German male",
        accent: "German",
        language: "German",
        locale: "de-DE",
        sex: "male",
        flagImageURL: "./images/germany_flag_round.png",
        flagImageAltText: "Germany flag",
    },
    {
        name: "Marlene",
        description: "German female",
        accent: "German",
        language: "German",
        locale: "de-DE",
        sex: "female",
        flagImageURL: "./images/germany_flag_round.png",
        flagImageAltText: "Germany flag",
    },
    {
        name: "Vicki",
        description: "German female two",
        accent: "German",
        language: "German",
        locale: "de-DE",
        sex: "female",
        flagImageURL: "./images/germany_flag_round.png",
        flagImageAltText: "Germany flag",
    },
    {
        name: "Giorgio",
        description: "Italian male",
        accent: "Italian",
        language: "Italian",
        locale: "it-IT",
        sex: "male",
        flagImageURL: "./images/italy_flag_round.png",
        flagImageAltText: "Italy flag",
    },
    {
        name: "Bianca",
        description: "Italian female",
        accent: "Italian",
        language: "Italian",
        locale: "it-IT",
        sex: "female",
        flagImageURL: "./images/italy_flag_round.png",
        flagImageAltText: "Italy flag",
    },
    {
        name: "Carla",
        description: "Italian female two",
        accent: "Italian",
        language: "Italian",
        locale: "it-IT",
        sex: "female",
        flagImageURL: "./images/italy_flag_round.png",
        flagImageAltText: "Italy flag",
    },
    {
        name: "Takumi",
        description: "Japanese male",
        accent: "Japanese",
        language: "Japanese",
        locale: "ja-JP",
        sex: "male",
        flagImageURL: "./images/japan_flag_round.png",
        flagImageAltText: "Japan flag",
    }, 
    {
        name: "Mizuki",
        description: "Japanese female",
        accent: "Japanese",
        language: "Japanese",
        locale: "ja-JP",
        sex: "female",
        flagImageURL: "./images/japan_flag_round.png",
        flagImageAltText: "Japan flag",
    },
    {
        name: "Ricardo",
        description: "Portuguese male",
        accent: "Portuguese",
        language: "Portuguese",
        locale: "pt-BR",
        sex: "male",
        flagImageURL: "./images/brazil_flag_round.png",
        flagImageAltText: "Brazil flag",
    },
    {
        name: "Camila",
        description: "Portuguese female",
        accent: "Portuguese",
        language: "Portuguese",
        locale: "pt-BR",
        sex: "female",
        flagImageURL: "./images/brazil_flag_round.png",
        flagImageAltText: "Brazil flag",
    },
    {
        name: "Vitoria",
        description: "Portuguese female two",
        accent: "Portuguese",
        language: "Portuguese",
        locale: "pt-BR",
        sex: "female",
        flagImageURL: "./images/brazil_flag_round.png",
        flagImageAltText: "Brazil flag",
    },
    {
        name: "Enrique",
        description: "Spanish male",
        accent: "Spanish",
        language: "Spanish",
        locale: "es-ES",
        sex: "male",
        flagImageURL: "./images/spain_flag_round.png",
        flagImageAltText: "Spain flag",
    },
    {
        name: "Conchita",
        description: "Spanish female",
        accent: "Spanish",
        language: "Spanish",
        locale: "es-ES",
        sex: "female",
        flagImageURL: "./images/spain_flag_round.png",
        flagImageAltText: "Spain flag",
    },
    {
        name: "Lucia",
        description: "Spanish female two",
        accent: "Spanish",
        language: "Spanish",
        locale: "es-ES",
        sex: "female",
        flagImageURL: "./images/spain_flag_round.png",
        flagImageAltText: "Spain flag",
    },
    {
        name: "Miguel",
        description: "Spanish male two",
        accent: "Spanish",
        language: "Spanish",
        locale: "es-US",
        sex: "male",
        flagImageURL: "./images/mexico_flag_round.png",
        flagImageAltText: "Mexico flag",
    },
    {
        name: "Lupe",
        description: "Spanish female three",
        accent: "Spanish",
        language: "Spanish",
        locale: "es-US",
        sex: "female",
        flagImageURL: "./images/mexico_flag_round.png",
        flagImageAltText: "Mexico flag",
    },
    {
        name: "Penelope",
        description: "Spanish female four",
        accent: "Spanish",
        language: "Spanish",
        locale: "es-US",
        sex: "female",
        flagImageURL: "./images/mexico_flag_round.png",
        flagImageAltText: "Mexico flag",
    },
    {
        name: "Mia",
        description: "Spanish female five",
        accent: "Mexican",
        language: "Spanish",
        locale: "es-MX",
        sex: "female",
        flagImageURL: "./images/mexico_flag_round.png",
        flagImageAltText: "Mexico flag",
    },
];

function getRandomVoice() {
    let i = Math.floor(Math.random() * voices.length);
    return voices[i];
}

module.exports = {
    getRandomVoice,
    voices
};
